#  Template NodeJS build

#  This template allows you to validate your NodeJS code.
#  The workflow allows running tests and code linting on the default branch.

image: node:16

pipelines:
  default:
    - step:
        name: Build and Test
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - yarn install
          - echo "Testing..."
          - yarn test

  branches:
    develop:
      - step:
          name: Testing
          script:
            - yarn install
            - echo "This will test develop branch..."
            - yarn test

      - step:
          name: Deploy to azure
          deployment: test
          trigger: manual  # Uncomment to make this a manual deployment.
          script:
            - echo "Deploying to azure environment"
            - cat ./deployment/develop.sh | ssh -T usjlab_ta@ml-lab-c7e2495d-9afa-4f83-ba2d-ef50ab41d52f.westeurope.cloudapp.azure.com -p 61142
