DROP TABLE IF EXISTS public.store;
DROP TABLE IF EXISTS public.customer;
DROP TABLE IF EXISTS public.admin;
DROP TABLE IF EXISTS public.auth;
DROP TABLE IF EXISTS public.prize;
DROP TABLE IF EXISTS public.store_customer;
DROP TABLE IF EXISTS public.history;

CREATE TABLE public.auth (
	name varchar NOT NULL,
	"password" varchar NOT NULL,
	email varchar NOT NULL,
	idauth int NOT NULL GENERATED BY DEFAULT AS IDENTITY
);

ALTER TABLE public.auth ADD CONSTRAINT auth_pk PRIMARY KEY (idauth);
ALTER TABLE public.auth ADD CONSTRAINT auth_uk UNIQUE  (email);

CREATE TABLE public.customer (
	iduser int NOT NULL,
	id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	birthdate date NULL,
	postcode varchar NOT NULL,
  CONSTRAINT customer_pk PRIMARY KEY (id)
);

CREATE TABLE public.store (
	iduser int NOT NULL,
	id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	sector varchar NOT NULL,
	phone int NOT NULL,
  CONSTRAINT store_pk PRIMARY KEY (id)
);

CREATE TABLE public.admin (
	iduser int NOT NULL,
	id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"role" varchar NOT NULL,
  CONSTRAINT admin_pk PRIMARY KEY (id)
);

CREATE TABLE public.store_customer (
	id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	idcustomer int NOT NULL,
	idstore int NOT NULL,
	points int NOT NULL
);

CREATE TABLE public.prize (
	id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	idstore int NOT NULL,
	name varchar NOT NULL,
	category varchar NOT NULL,
	points int NOT NULL
);

CREATE TABLE public.history (
	id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"date" date NOT NULL,
	idcustomer int NOT NULL,
	age int NOT NULL,
	idstore int NOT NULL,
	sector varchar NOT NULL,
	idprize int NOT NULL,
	points int NOT NULL,
	name varchar NOT NULL,
	category varchar NOT NULL
);